apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
spec:
  replicas: 1
  template:
    metadata:
      name: provider
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: provider
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: 'K8S_TIMESTAMP'
            - name: spring.cloud.nacos.discovery.server-addr
              value: nacos:8848
      restartPolicy: Always
  selector:
    matchLabels:
      app: provider

---
apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app: provider
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: provider